import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Bell, Search, Menu, X } from 'lucide-react';
import { useState } from 'react';
const DashboardHeader = () => {
    const [isSearchOpen, setIsSearchOpen] = useState(false);
    const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);
    return (_jsx("header", { className: "bg-white border-b border-gray-200", children: _jsxs("div", { className: "px-6 py-4", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center space-x-4", children: [_jsx("button", { onClick: () => setIsMobileMenuOpen(!isMobileMenuOpen), className: "lg:hidden p-2 rounded-lg hover:bg-gray-100", children: isMobileMenuOpen ? (_jsx(X, { className: "h-5 w-5" })) : (_jsx(Menu, { className: "h-5 w-5" })) }), _jsxs("div", { className: "relative hidden lg:block", children: [_jsx("div", { className: "absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none", children: _jsx(Search, { className: "h-5 w-5 text-gray-400" }) }), _jsx("input", { type: "search", placeholder: "Search...", className: "pl-10 pr-4 py-2 w-64 lg:w-96 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500" })] }), _jsx("button", { onClick: () => setIsSearchOpen(true), className: "lg:hidden p-2 rounded-lg hover:bg-gray-100", children: _jsx(Search, { className: "h-5 w-5" }) })] }), _jsxs("div", { className: "flex items-center space-x-4", children: [_jsxs("button", { className: "relative p-2 rounded-lg hover:bg-gray-100", children: [_jsx(Bell, { className: "h-5 w-5" }), _jsx("span", { className: "absolute top-1 right-1 w-2 h-2 bg-red-500 rounded-full" })] }), _jsx("div", { className: "relative", children: _jsxs("button", { className: "flex items-center space-x-3 p-2 rounded-lg hover:bg-gray-100", children: [_jsx("div", { className: "w-8 h-8 bg-blue-100 rounded-full flex items-center justify-center", children: _jsx("span", { className: "font-semibold text-blue-600", children: "JD" }) }), _jsxs("div", { className: "hidden md:block text-left", children: [_jsx("p", { className: "text-sm font-medium", children: "John Doe" }), _jsx("p", { className: "text-xs text-gray-500", children: "Student" })] })] }) })] })] }), isSearchOpen && (_jsx("div", { className: "mt-4 lg:hidden", children: _jsxs("div", { className: "relative", children: [_jsx("input", { type: "search", placeholder: "Search...", className: "w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500", autoFocus: true, onBlur: () => setIsSearchOpen(false) }), _jsx("div", { className: "absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none", children: _jsx(Search, { className: "h-5 w-5 text-gray-400" }) })] }) }))] }) }));
};
export default DashboardHeader;
